name: 'Build ResoniteLink'
author: 'Jae'
description: 'Builds a NuGet package for ResoniteLink'

inputs:
  dotnet-version:
    description: 'Version of dotnet to use'
    default: '10.0.x'
    required: false
  additional-args:
    description: 'Additional args to pass to build'
    required: false
    default: ''
  out-folder:
    description: 'Folder to output nugets in'
    required: false
    default: 'nupkgs'
  projectdir:
    description: 'Directory of the project to build'
    default: 'ResoniteLink'
    required: false

runs:
  using: composite
  steps:
    - name: 'Install Dotnet'
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: 'Build library'
      shell: bash
      run: dotnet pack ${{ inputs.projectdir }} --output nupkgs -c Release ${{ inputs.additional-args }}
