
// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!


using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;

namespace ResoniteLink
{
    
        public class Field_byte : Field
        {
            [JsonPropertyName("value")]
            public byte Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (byte)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(byte);
        }

        public class Array_byte : SyncArray
        {
            [JsonPropertyName("values")]
            public List<byte> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(byte);
        }

        [JsonDerivedType(typeof(Field_byte), "byte")]
        [JsonDerivedType(typeof(Array_byte), "byte[]")]
        public partial class Member { }

                    public class Field_Nullable_byte : Field
            {
                [JsonPropertyName("value")]
                public byte? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as byte?; }

                [JsonIgnore]
                public override Type ValueType => typeof(byte?);
            }

            [JsonDerivedType(typeof(Field_Nullable_byte), "byte?")]
            public partial class Member { }
            
        
        public class Field_ushort : Field
        {
            [JsonPropertyName("value")]
            public ushort Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (ushort)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(ushort);
        }

        public class Array_ushort : SyncArray
        {
            [JsonPropertyName("values")]
            public List<ushort> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(ushort);
        }

        [JsonDerivedType(typeof(Field_ushort), "ushort")]
        [JsonDerivedType(typeof(Array_ushort), "ushort[]")]
        public partial class Member { }

                    public class Field_Nullable_ushort : Field
            {
                [JsonPropertyName("value")]
                public ushort? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as ushort?; }

                [JsonIgnore]
                public override Type ValueType => typeof(ushort?);
            }

            [JsonDerivedType(typeof(Field_Nullable_ushort), "ushort?")]
            public partial class Member { }
            
        
        public class Field_uint : Field
        {
            [JsonPropertyName("value")]
            public uint Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (uint)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(uint);
        }

        public class Array_uint : SyncArray
        {
            [JsonPropertyName("values")]
            public List<uint> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(uint);
        }

        [JsonDerivedType(typeof(Field_uint), "uint")]
        [JsonDerivedType(typeof(Array_uint), "uint[]")]
        public partial class Member { }

                    public class Field_Nullable_uint : Field
            {
                [JsonPropertyName("value")]
                public uint? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as uint?; }

                [JsonIgnore]
                public override Type ValueType => typeof(uint?);
            }

            [JsonDerivedType(typeof(Field_Nullable_uint), "uint?")]
            public partial class Member { }
            
        
        public class Field_ulong : Field
        {
            [JsonPropertyName("value")]
            public ulong Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (ulong)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(ulong);
        }

        public class Array_ulong : SyncArray
        {
            [JsonPropertyName("values")]
            public List<ulong> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(ulong);
        }

        [JsonDerivedType(typeof(Field_ulong), "ulong")]
        [JsonDerivedType(typeof(Array_ulong), "ulong[]")]
        public partial class Member { }

                    public class Field_Nullable_ulong : Field
            {
                [JsonPropertyName("value")]
                public ulong? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as ulong?; }

                [JsonIgnore]
                public override Type ValueType => typeof(ulong?);
            }

            [JsonDerivedType(typeof(Field_Nullable_ulong), "ulong?")]
            public partial class Member { }
            
        
        public class Field_sbyte : Field
        {
            [JsonPropertyName("value")]
            public sbyte Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (sbyte)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(sbyte);
        }

        public class Array_sbyte : SyncArray
        {
            [JsonPropertyName("values")]
            public List<sbyte> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(sbyte);
        }

        [JsonDerivedType(typeof(Field_sbyte), "sbyte")]
        [JsonDerivedType(typeof(Array_sbyte), "sbyte[]")]
        public partial class Member { }

                    public class Field_Nullable_sbyte : Field
            {
                [JsonPropertyName("value")]
                public sbyte? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as sbyte?; }

                [JsonIgnore]
                public override Type ValueType => typeof(sbyte?);
            }

            [JsonDerivedType(typeof(Field_Nullable_sbyte), "sbyte?")]
            public partial class Member { }
            
        
        public class Field_short : Field
        {
            [JsonPropertyName("value")]
            public short Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (short)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(short);
        }

        public class Array_short : SyncArray
        {
            [JsonPropertyName("values")]
            public List<short> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(short);
        }

        [JsonDerivedType(typeof(Field_short), "short")]
        [JsonDerivedType(typeof(Array_short), "short[]")]
        public partial class Member { }

                    public class Field_Nullable_short : Field
            {
                [JsonPropertyName("value")]
                public short? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as short?; }

                [JsonIgnore]
                public override Type ValueType => typeof(short?);
            }

            [JsonDerivedType(typeof(Field_Nullable_short), "short?")]
            public partial class Member { }
            
        
        public class Field_int : Field
        {
            [JsonPropertyName("value")]
            public int Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (int)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(int);
        }

        public class Array_int : SyncArray
        {
            [JsonPropertyName("values")]
            public List<int> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(int);
        }

        [JsonDerivedType(typeof(Field_int), "int")]
        [JsonDerivedType(typeof(Array_int), "int[]")]
        public partial class Member { }

                    public class Field_Nullable_int : Field
            {
                [JsonPropertyName("value")]
                public int? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as int?; }

                [JsonIgnore]
                public override Type ValueType => typeof(int?);
            }

            [JsonDerivedType(typeof(Field_Nullable_int), "int?")]
            public partial class Member { }
            
        
        public class Field_long : Field
        {
            [JsonPropertyName("value")]
            public long Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (long)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(long);
        }

        public class Array_long : SyncArray
        {
            [JsonPropertyName("values")]
            public List<long> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(long);
        }

        [JsonDerivedType(typeof(Field_long), "long")]
        [JsonDerivedType(typeof(Array_long), "long[]")]
        public partial class Member { }

                    public class Field_Nullable_long : Field
            {
                [JsonPropertyName("value")]
                public long? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as long?; }

                [JsonIgnore]
                public override Type ValueType => typeof(long?);
            }

            [JsonDerivedType(typeof(Field_Nullable_long), "long?")]
            public partial class Member { }
            
        
        public class Field_float : Field
        {
            [JsonPropertyName("value")]
            public float Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (float)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(float);
        }

        public class Array_float : SyncArray
        {
            [JsonPropertyName("values")]
            public List<float> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(float);
        }

        [JsonDerivedType(typeof(Field_float), "float")]
        [JsonDerivedType(typeof(Array_float), "float[]")]
        public partial class Member { }

                    public class Field_Nullable_float : Field
            {
                [JsonPropertyName("value")]
                public float? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as float?; }

                [JsonIgnore]
                public override Type ValueType => typeof(float?);
            }

            [JsonDerivedType(typeof(Field_Nullable_float), "float?")]
            public partial class Member { }
            
        
        public class Field_double : Field
        {
            [JsonPropertyName("value")]
            public double Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (double)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(double);
        }

        public class Array_double : SyncArray
        {
            [JsonPropertyName("values")]
            public List<double> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(double);
        }

        [JsonDerivedType(typeof(Field_double), "double")]
        [JsonDerivedType(typeof(Array_double), "double[]")]
        public partial class Member { }

                    public class Field_Nullable_double : Field
            {
                [JsonPropertyName("value")]
                public double? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as double?; }

                [JsonIgnore]
                public override Type ValueType => typeof(double?);
            }

            [JsonDerivedType(typeof(Field_Nullable_double), "double?")]
            public partial class Member { }
            
        
        public class Field_decimal : Field
        {
            [JsonPropertyName("value")]
            public decimal Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (decimal)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(decimal);
        }

        public class Array_decimal : SyncArray
        {
            [JsonPropertyName("values")]
            public List<decimal> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(decimal);
        }

        [JsonDerivedType(typeof(Field_decimal), "decimal")]
        [JsonDerivedType(typeof(Array_decimal), "decimal[]")]
        public partial class Member { }

                    public class Field_Nullable_decimal : Field
            {
                [JsonPropertyName("value")]
                public decimal? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as decimal?; }

                [JsonIgnore]
                public override Type ValueType => typeof(decimal?);
            }

            [JsonDerivedType(typeof(Field_Nullable_decimal), "decimal?")]
            public partial class Member { }
            
        
        public class Field_bool : Field
        {
            [JsonPropertyName("value")]
            public bool Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (bool)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(bool);
        }

        public class Array_bool : SyncArray
        {
            [JsonPropertyName("values")]
            public List<bool> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(bool);
        }

        [JsonDerivedType(typeof(Field_bool), "bool")]
        [JsonDerivedType(typeof(Array_bool), "bool[]")]
        public partial class Member { }

                    public class Field_Nullable_bool : Field
            {
                [JsonPropertyName("value")]
                public bool? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as bool?; }

                [JsonIgnore]
                public override Type ValueType => typeof(bool?);
            }

            [JsonDerivedType(typeof(Field_Nullable_bool), "bool?")]
            public partial class Member { }
            
        
        public class Field_char : Field
        {
            [JsonPropertyName("value")]
            public char Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (char)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(char);
        }

        public class Array_char : SyncArray
        {
            [JsonPropertyName("values")]
            public List<char> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(char);
        }

        [JsonDerivedType(typeof(Field_char), "char")]
        [JsonDerivedType(typeof(Array_char), "char[]")]
        public partial class Member { }

                    public class Field_Nullable_char : Field
            {
                [JsonPropertyName("value")]
                public char? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as char?; }

                [JsonIgnore]
                public override Type ValueType => typeof(char?);
            }

            [JsonDerivedType(typeof(Field_Nullable_char), "char?")]
            public partial class Member { }
            
        
        public class Field_string : Field
        {
            [JsonPropertyName("value")]
            public string Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (string)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(string);
        }

        public class Array_string : SyncArray
        {
            [JsonPropertyName("values")]
            public List<string> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(string);
        }

        [JsonDerivedType(typeof(Field_string), "string")]
        [JsonDerivedType(typeof(Array_string), "string[]")]
        public partial class Member { }

        
        
        public class Field_Uri : Field
        {
            [JsonPropertyName("value")]
            public Uri Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (Uri)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(Uri);
        }

        public class Array_Uri : SyncArray
        {
            [JsonPropertyName("values")]
            public List<Uri> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(Uri);
        }

        [JsonDerivedType(typeof(Field_Uri), "Uri")]
        [JsonDerivedType(typeof(Array_Uri), "Uri[]")]
        public partial class Member { }

        
        
        public class Field_color : Field
        {
            [JsonPropertyName("value")]
            public color Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (color)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(color);
        }

        public class Array_color : SyncArray
        {
            [JsonPropertyName("values")]
            public List<color> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(color);
        }

        [JsonDerivedType(typeof(Field_color), "color")]
        [JsonDerivedType(typeof(Array_color), "color[]")]
        public partial class Member { }

                    public class Field_Nullable_color : Field
            {
                [JsonPropertyName("value")]
                public color? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as color?; }

                [JsonIgnore]
                public override Type ValueType => typeof(color?);
            }

            [JsonDerivedType(typeof(Field_Nullable_color), "color?")]
            public partial class Member { }
            
        
        public class Field_colorX : Field
        {
            [JsonPropertyName("value")]
            public colorX Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (colorX)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(colorX);
        }

        public class Array_colorX : SyncArray
        {
            [JsonPropertyName("values")]
            public List<colorX> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(colorX);
        }

        [JsonDerivedType(typeof(Field_colorX), "colorX")]
        [JsonDerivedType(typeof(Array_colorX), "colorX[]")]
        public partial class Member { }

                    public class Field_Nullable_colorX : Field
            {
                [JsonPropertyName("value")]
                public colorX? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as colorX?; }

                [JsonIgnore]
                public override Type ValueType => typeof(colorX?);
            }

            [JsonDerivedType(typeof(Field_Nullable_colorX), "colorX?")]
            public partial class Member { }
            
        
        public class Field_color32 : Field
        {
            [JsonPropertyName("value")]
            public color32 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (color32)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(color32);
        }

        public class Array_color32 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<color32> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(color32);
        }

        [JsonDerivedType(typeof(Field_color32), "color32")]
        [JsonDerivedType(typeof(Array_color32), "color32[]")]
        public partial class Member { }

                    public class Field_Nullable_color32 : Field
            {
                [JsonPropertyName("value")]
                public color32? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as color32?; }

                [JsonIgnore]
                public override Type ValueType => typeof(color32?);
            }

            [JsonDerivedType(typeof(Field_Nullable_color32), "color32?")]
            public partial class Member { }
            
        
        public class Field_float2 : Field
        {
            [JsonPropertyName("value")]
            public float2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (float2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(float2);
        }

        public class Array_float2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<float2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(float2);
        }

        [JsonDerivedType(typeof(Field_float2), "float2")]
        [JsonDerivedType(typeof(Array_float2), "float2[]")]
        public partial class Member { }

                    public class Field_Nullable_float2 : Field
            {
                [JsonPropertyName("value")]
                public float2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as float2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(float2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_float2), "float2?")]
            public partial class Member { }
            
        
        public class Field_double2 : Field
        {
            [JsonPropertyName("value")]
            public double2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (double2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(double2);
        }

        public class Array_double2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<double2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(double2);
        }

        [JsonDerivedType(typeof(Field_double2), "double2")]
        [JsonDerivedType(typeof(Array_double2), "double2[]")]
        public partial class Member { }

                    public class Field_Nullable_double2 : Field
            {
                [JsonPropertyName("value")]
                public double2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as double2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(double2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_double2), "double2?")]
            public partial class Member { }
            
        
        public class Field_byte2 : Field
        {
            [JsonPropertyName("value")]
            public byte2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (byte2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(byte2);
        }

        public class Array_byte2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<byte2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(byte2);
        }

        [JsonDerivedType(typeof(Field_byte2), "byte2")]
        [JsonDerivedType(typeof(Array_byte2), "byte2[]")]
        public partial class Member { }

                    public class Field_Nullable_byte2 : Field
            {
                [JsonPropertyName("value")]
                public byte2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as byte2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(byte2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_byte2), "byte2?")]
            public partial class Member { }
            
        
        public class Field_ushort2 : Field
        {
            [JsonPropertyName("value")]
            public ushort2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (ushort2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(ushort2);
        }

        public class Array_ushort2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<ushort2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(ushort2);
        }

        [JsonDerivedType(typeof(Field_ushort2), "ushort2")]
        [JsonDerivedType(typeof(Array_ushort2), "ushort2[]")]
        public partial class Member { }

                    public class Field_Nullable_ushort2 : Field
            {
                [JsonPropertyName("value")]
                public ushort2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as ushort2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(ushort2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_ushort2), "ushort2?")]
            public partial class Member { }
            
        
        public class Field_uint2 : Field
        {
            [JsonPropertyName("value")]
            public uint2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (uint2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(uint2);
        }

        public class Array_uint2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<uint2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(uint2);
        }

        [JsonDerivedType(typeof(Field_uint2), "uint2")]
        [JsonDerivedType(typeof(Array_uint2), "uint2[]")]
        public partial class Member { }

                    public class Field_Nullable_uint2 : Field
            {
                [JsonPropertyName("value")]
                public uint2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as uint2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(uint2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_uint2), "uint2?")]
            public partial class Member { }
            
        
        public class Field_ulong2 : Field
        {
            [JsonPropertyName("value")]
            public ulong2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (ulong2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(ulong2);
        }

        public class Array_ulong2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<ulong2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(ulong2);
        }

        [JsonDerivedType(typeof(Field_ulong2), "ulong2")]
        [JsonDerivedType(typeof(Array_ulong2), "ulong2[]")]
        public partial class Member { }

                    public class Field_Nullable_ulong2 : Field
            {
                [JsonPropertyName("value")]
                public ulong2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as ulong2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(ulong2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_ulong2), "ulong2?")]
            public partial class Member { }
            
        
        public class Field_sbyte2 : Field
        {
            [JsonPropertyName("value")]
            public sbyte2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (sbyte2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(sbyte2);
        }

        public class Array_sbyte2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<sbyte2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(sbyte2);
        }

        [JsonDerivedType(typeof(Field_sbyte2), "sbyte2")]
        [JsonDerivedType(typeof(Array_sbyte2), "sbyte2[]")]
        public partial class Member { }

                    public class Field_Nullable_sbyte2 : Field
            {
                [JsonPropertyName("value")]
                public sbyte2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as sbyte2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(sbyte2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_sbyte2), "sbyte2?")]
            public partial class Member { }
            
        
        public class Field_short2 : Field
        {
            [JsonPropertyName("value")]
            public short2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (short2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(short2);
        }

        public class Array_short2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<short2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(short2);
        }

        [JsonDerivedType(typeof(Field_short2), "short2")]
        [JsonDerivedType(typeof(Array_short2), "short2[]")]
        public partial class Member { }

                    public class Field_Nullable_short2 : Field
            {
                [JsonPropertyName("value")]
                public short2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as short2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(short2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_short2), "short2?")]
            public partial class Member { }
            
        
        public class Field_int2 : Field
        {
            [JsonPropertyName("value")]
            public int2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (int2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(int2);
        }

        public class Array_int2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<int2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(int2);
        }

        [JsonDerivedType(typeof(Field_int2), "int2")]
        [JsonDerivedType(typeof(Array_int2), "int2[]")]
        public partial class Member { }

                    public class Field_Nullable_int2 : Field
            {
                [JsonPropertyName("value")]
                public int2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as int2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(int2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_int2), "int2?")]
            public partial class Member { }
            
        
        public class Field_long2 : Field
        {
            [JsonPropertyName("value")]
            public long2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (long2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(long2);
        }

        public class Array_long2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<long2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(long2);
        }

        [JsonDerivedType(typeof(Field_long2), "long2")]
        [JsonDerivedType(typeof(Array_long2), "long2[]")]
        public partial class Member { }

                    public class Field_Nullable_long2 : Field
            {
                [JsonPropertyName("value")]
                public long2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as long2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(long2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_long2), "long2?")]
            public partial class Member { }
            
        
        public class Field_bool2 : Field
        {
            [JsonPropertyName("value")]
            public bool2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (bool2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(bool2);
        }

        public class Array_bool2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<bool2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(bool2);
        }

        [JsonDerivedType(typeof(Field_bool2), "bool2")]
        [JsonDerivedType(typeof(Array_bool2), "bool2[]")]
        public partial class Member { }

                    public class Field_Nullable_bool2 : Field
            {
                [JsonPropertyName("value")]
                public bool2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as bool2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(bool2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_bool2), "bool2?")]
            public partial class Member { }
            
        
        public class Field_float3 : Field
        {
            [JsonPropertyName("value")]
            public float3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (float3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(float3);
        }

        public class Array_float3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<float3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(float3);
        }

        [JsonDerivedType(typeof(Field_float3), "float3")]
        [JsonDerivedType(typeof(Array_float3), "float3[]")]
        public partial class Member { }

                    public class Field_Nullable_float3 : Field
            {
                [JsonPropertyName("value")]
                public float3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as float3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(float3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_float3), "float3?")]
            public partial class Member { }
            
        
        public class Field_double3 : Field
        {
            [JsonPropertyName("value")]
            public double3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (double3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(double3);
        }

        public class Array_double3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<double3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(double3);
        }

        [JsonDerivedType(typeof(Field_double3), "double3")]
        [JsonDerivedType(typeof(Array_double3), "double3[]")]
        public partial class Member { }

                    public class Field_Nullable_double3 : Field
            {
                [JsonPropertyName("value")]
                public double3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as double3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(double3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_double3), "double3?")]
            public partial class Member { }
            
        
        public class Field_byte3 : Field
        {
            [JsonPropertyName("value")]
            public byte3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (byte3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(byte3);
        }

        public class Array_byte3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<byte3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(byte3);
        }

        [JsonDerivedType(typeof(Field_byte3), "byte3")]
        [JsonDerivedType(typeof(Array_byte3), "byte3[]")]
        public partial class Member { }

                    public class Field_Nullable_byte3 : Field
            {
                [JsonPropertyName("value")]
                public byte3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as byte3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(byte3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_byte3), "byte3?")]
            public partial class Member { }
            
        
        public class Field_ushort3 : Field
        {
            [JsonPropertyName("value")]
            public ushort3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (ushort3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(ushort3);
        }

        public class Array_ushort3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<ushort3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(ushort3);
        }

        [JsonDerivedType(typeof(Field_ushort3), "ushort3")]
        [JsonDerivedType(typeof(Array_ushort3), "ushort3[]")]
        public partial class Member { }

                    public class Field_Nullable_ushort3 : Field
            {
                [JsonPropertyName("value")]
                public ushort3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as ushort3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(ushort3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_ushort3), "ushort3?")]
            public partial class Member { }
            
        
        public class Field_uint3 : Field
        {
            [JsonPropertyName("value")]
            public uint3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (uint3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(uint3);
        }

        public class Array_uint3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<uint3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(uint3);
        }

        [JsonDerivedType(typeof(Field_uint3), "uint3")]
        [JsonDerivedType(typeof(Array_uint3), "uint3[]")]
        public partial class Member { }

                    public class Field_Nullable_uint3 : Field
            {
                [JsonPropertyName("value")]
                public uint3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as uint3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(uint3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_uint3), "uint3?")]
            public partial class Member { }
            
        
        public class Field_ulong3 : Field
        {
            [JsonPropertyName("value")]
            public ulong3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (ulong3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(ulong3);
        }

        public class Array_ulong3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<ulong3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(ulong3);
        }

        [JsonDerivedType(typeof(Field_ulong3), "ulong3")]
        [JsonDerivedType(typeof(Array_ulong3), "ulong3[]")]
        public partial class Member { }

                    public class Field_Nullable_ulong3 : Field
            {
                [JsonPropertyName("value")]
                public ulong3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as ulong3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(ulong3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_ulong3), "ulong3?")]
            public partial class Member { }
            
        
        public class Field_sbyte3 : Field
        {
            [JsonPropertyName("value")]
            public sbyte3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (sbyte3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(sbyte3);
        }

        public class Array_sbyte3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<sbyte3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(sbyte3);
        }

        [JsonDerivedType(typeof(Field_sbyte3), "sbyte3")]
        [JsonDerivedType(typeof(Array_sbyte3), "sbyte3[]")]
        public partial class Member { }

                    public class Field_Nullable_sbyte3 : Field
            {
                [JsonPropertyName("value")]
                public sbyte3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as sbyte3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(sbyte3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_sbyte3), "sbyte3?")]
            public partial class Member { }
            
        
        public class Field_short3 : Field
        {
            [JsonPropertyName("value")]
            public short3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (short3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(short3);
        }

        public class Array_short3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<short3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(short3);
        }

        [JsonDerivedType(typeof(Field_short3), "short3")]
        [JsonDerivedType(typeof(Array_short3), "short3[]")]
        public partial class Member { }

                    public class Field_Nullable_short3 : Field
            {
                [JsonPropertyName("value")]
                public short3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as short3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(short3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_short3), "short3?")]
            public partial class Member { }
            
        
        public class Field_int3 : Field
        {
            [JsonPropertyName("value")]
            public int3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (int3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(int3);
        }

        public class Array_int3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<int3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(int3);
        }

        [JsonDerivedType(typeof(Field_int3), "int3")]
        [JsonDerivedType(typeof(Array_int3), "int3[]")]
        public partial class Member { }

                    public class Field_Nullable_int3 : Field
            {
                [JsonPropertyName("value")]
                public int3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as int3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(int3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_int3), "int3?")]
            public partial class Member { }
            
        
        public class Field_long3 : Field
        {
            [JsonPropertyName("value")]
            public long3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (long3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(long3);
        }

        public class Array_long3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<long3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(long3);
        }

        [JsonDerivedType(typeof(Field_long3), "long3")]
        [JsonDerivedType(typeof(Array_long3), "long3[]")]
        public partial class Member { }

                    public class Field_Nullable_long3 : Field
            {
                [JsonPropertyName("value")]
                public long3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as long3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(long3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_long3), "long3?")]
            public partial class Member { }
            
        
        public class Field_bool3 : Field
        {
            [JsonPropertyName("value")]
            public bool3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (bool3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(bool3);
        }

        public class Array_bool3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<bool3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(bool3);
        }

        [JsonDerivedType(typeof(Field_bool3), "bool3")]
        [JsonDerivedType(typeof(Array_bool3), "bool3[]")]
        public partial class Member { }

                    public class Field_Nullable_bool3 : Field
            {
                [JsonPropertyName("value")]
                public bool3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as bool3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(bool3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_bool3), "bool3?")]
            public partial class Member { }
            
        
        public class Field_float4 : Field
        {
            [JsonPropertyName("value")]
            public float4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (float4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(float4);
        }

        public class Array_float4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<float4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(float4);
        }

        [JsonDerivedType(typeof(Field_float4), "float4")]
        [JsonDerivedType(typeof(Array_float4), "float4[]")]
        public partial class Member { }

                    public class Field_Nullable_float4 : Field
            {
                [JsonPropertyName("value")]
                public float4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as float4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(float4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_float4), "float4?")]
            public partial class Member { }
            
        
        public class Field_double4 : Field
        {
            [JsonPropertyName("value")]
            public double4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (double4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(double4);
        }

        public class Array_double4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<double4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(double4);
        }

        [JsonDerivedType(typeof(Field_double4), "double4")]
        [JsonDerivedType(typeof(Array_double4), "double4[]")]
        public partial class Member { }

                    public class Field_Nullable_double4 : Field
            {
                [JsonPropertyName("value")]
                public double4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as double4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(double4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_double4), "double4?")]
            public partial class Member { }
            
        
        public class Field_byte4 : Field
        {
            [JsonPropertyName("value")]
            public byte4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (byte4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(byte4);
        }

        public class Array_byte4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<byte4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(byte4);
        }

        [JsonDerivedType(typeof(Field_byte4), "byte4")]
        [JsonDerivedType(typeof(Array_byte4), "byte4[]")]
        public partial class Member { }

                    public class Field_Nullable_byte4 : Field
            {
                [JsonPropertyName("value")]
                public byte4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as byte4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(byte4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_byte4), "byte4?")]
            public partial class Member { }
            
        
        public class Field_ushort4 : Field
        {
            [JsonPropertyName("value")]
            public ushort4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (ushort4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(ushort4);
        }

        public class Array_ushort4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<ushort4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(ushort4);
        }

        [JsonDerivedType(typeof(Field_ushort4), "ushort4")]
        [JsonDerivedType(typeof(Array_ushort4), "ushort4[]")]
        public partial class Member { }

                    public class Field_Nullable_ushort4 : Field
            {
                [JsonPropertyName("value")]
                public ushort4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as ushort4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(ushort4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_ushort4), "ushort4?")]
            public partial class Member { }
            
        
        public class Field_uint4 : Field
        {
            [JsonPropertyName("value")]
            public uint4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (uint4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(uint4);
        }

        public class Array_uint4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<uint4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(uint4);
        }

        [JsonDerivedType(typeof(Field_uint4), "uint4")]
        [JsonDerivedType(typeof(Array_uint4), "uint4[]")]
        public partial class Member { }

                    public class Field_Nullable_uint4 : Field
            {
                [JsonPropertyName("value")]
                public uint4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as uint4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(uint4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_uint4), "uint4?")]
            public partial class Member { }
            
        
        public class Field_ulong4 : Field
        {
            [JsonPropertyName("value")]
            public ulong4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (ulong4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(ulong4);
        }

        public class Array_ulong4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<ulong4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(ulong4);
        }

        [JsonDerivedType(typeof(Field_ulong4), "ulong4")]
        [JsonDerivedType(typeof(Array_ulong4), "ulong4[]")]
        public partial class Member { }

                    public class Field_Nullable_ulong4 : Field
            {
                [JsonPropertyName("value")]
                public ulong4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as ulong4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(ulong4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_ulong4), "ulong4?")]
            public partial class Member { }
            
        
        public class Field_sbyte4 : Field
        {
            [JsonPropertyName("value")]
            public sbyte4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (sbyte4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(sbyte4);
        }

        public class Array_sbyte4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<sbyte4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(sbyte4);
        }

        [JsonDerivedType(typeof(Field_sbyte4), "sbyte4")]
        [JsonDerivedType(typeof(Array_sbyte4), "sbyte4[]")]
        public partial class Member { }

                    public class Field_Nullable_sbyte4 : Field
            {
                [JsonPropertyName("value")]
                public sbyte4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as sbyte4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(sbyte4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_sbyte4), "sbyte4?")]
            public partial class Member { }
            
        
        public class Field_short4 : Field
        {
            [JsonPropertyName("value")]
            public short4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (short4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(short4);
        }

        public class Array_short4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<short4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(short4);
        }

        [JsonDerivedType(typeof(Field_short4), "short4")]
        [JsonDerivedType(typeof(Array_short4), "short4[]")]
        public partial class Member { }

                    public class Field_Nullable_short4 : Field
            {
                [JsonPropertyName("value")]
                public short4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as short4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(short4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_short4), "short4?")]
            public partial class Member { }
            
        
        public class Field_int4 : Field
        {
            [JsonPropertyName("value")]
            public int4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (int4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(int4);
        }

        public class Array_int4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<int4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(int4);
        }

        [JsonDerivedType(typeof(Field_int4), "int4")]
        [JsonDerivedType(typeof(Array_int4), "int4[]")]
        public partial class Member { }

                    public class Field_Nullable_int4 : Field
            {
                [JsonPropertyName("value")]
                public int4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as int4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(int4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_int4), "int4?")]
            public partial class Member { }
            
        
        public class Field_long4 : Field
        {
            [JsonPropertyName("value")]
            public long4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (long4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(long4);
        }

        public class Array_long4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<long4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(long4);
        }

        [JsonDerivedType(typeof(Field_long4), "long4")]
        [JsonDerivedType(typeof(Array_long4), "long4[]")]
        public partial class Member { }

                    public class Field_Nullable_long4 : Field
            {
                [JsonPropertyName("value")]
                public long4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as long4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(long4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_long4), "long4?")]
            public partial class Member { }
            
        
        public class Field_bool4 : Field
        {
            [JsonPropertyName("value")]
            public bool4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (bool4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(bool4);
        }

        public class Array_bool4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<bool4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(bool4);
        }

        [JsonDerivedType(typeof(Field_bool4), "bool4")]
        [JsonDerivedType(typeof(Array_bool4), "bool4[]")]
        public partial class Member { }

                    public class Field_Nullable_bool4 : Field
            {
                [JsonPropertyName("value")]
                public bool4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as bool4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(bool4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_bool4), "bool4?")]
            public partial class Member { }
            
        
        public class Field_floatQ : Field
        {
            [JsonPropertyName("value")]
            public floatQ Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (floatQ)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(floatQ);
        }

        public class Array_floatQ : SyncArray
        {
            [JsonPropertyName("values")]
            public List<floatQ> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(floatQ);
        }

        [JsonDerivedType(typeof(Field_floatQ), "floatQ")]
        [JsonDerivedType(typeof(Array_floatQ), "floatQ[]")]
        public partial class Member { }

                    public class Field_Nullable_floatQ : Field
            {
                [JsonPropertyName("value")]
                public floatQ? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as floatQ?; }

                [JsonIgnore]
                public override Type ValueType => typeof(floatQ?);
            }

            [JsonDerivedType(typeof(Field_Nullable_floatQ), "floatQ?")]
            public partial class Member { }
            
        
        public class Field_doubleQ : Field
        {
            [JsonPropertyName("value")]
            public doubleQ Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (doubleQ)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(doubleQ);
        }

        public class Array_doubleQ : SyncArray
        {
            [JsonPropertyName("values")]
            public List<doubleQ> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(doubleQ);
        }

        [JsonDerivedType(typeof(Field_doubleQ), "doubleQ")]
        [JsonDerivedType(typeof(Array_doubleQ), "doubleQ[]")]
        public partial class Member { }

                    public class Field_Nullable_doubleQ : Field
            {
                [JsonPropertyName("value")]
                public doubleQ? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as doubleQ?; }

                [JsonIgnore]
                public override Type ValueType => typeof(doubleQ?);
            }

            [JsonDerivedType(typeof(Field_Nullable_doubleQ), "doubleQ?")]
            public partial class Member { }
            
        
        public class Field_float2x2 : Field
        {
            [JsonPropertyName("value")]
            public float2x2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (float2x2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(float2x2);
        }

        public class Array_float2x2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<float2x2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(float2x2);
        }

        [JsonDerivedType(typeof(Field_float2x2), "float2x2")]
        [JsonDerivedType(typeof(Array_float2x2), "float2x2[]")]
        public partial class Member { }

                    public class Field_Nullable_float2x2 : Field
            {
                [JsonPropertyName("value")]
                public float2x2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as float2x2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(float2x2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_float2x2), "float2x2?")]
            public partial class Member { }
            
        
        public class Field_double2x2 : Field
        {
            [JsonPropertyName("value")]
            public double2x2 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (double2x2)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(double2x2);
        }

        public class Array_double2x2 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<double2x2> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(double2x2);
        }

        [JsonDerivedType(typeof(Field_double2x2), "double2x2")]
        [JsonDerivedType(typeof(Array_double2x2), "double2x2[]")]
        public partial class Member { }

                    public class Field_Nullable_double2x2 : Field
            {
                [JsonPropertyName("value")]
                public double2x2? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as double2x2?; }

                [JsonIgnore]
                public override Type ValueType => typeof(double2x2?);
            }

            [JsonDerivedType(typeof(Field_Nullable_double2x2), "double2x2?")]
            public partial class Member { }
            
        
        public class Field_float3x3 : Field
        {
            [JsonPropertyName("value")]
            public float3x3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (float3x3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(float3x3);
        }

        public class Array_float3x3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<float3x3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(float3x3);
        }

        [JsonDerivedType(typeof(Field_float3x3), "float3x3")]
        [JsonDerivedType(typeof(Array_float3x3), "float3x3[]")]
        public partial class Member { }

                    public class Field_Nullable_float3x3 : Field
            {
                [JsonPropertyName("value")]
                public float3x3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as float3x3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(float3x3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_float3x3), "float3x3?")]
            public partial class Member { }
            
        
        public class Field_double3x3 : Field
        {
            [JsonPropertyName("value")]
            public double3x3 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (double3x3)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(double3x3);
        }

        public class Array_double3x3 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<double3x3> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(double3x3);
        }

        [JsonDerivedType(typeof(Field_double3x3), "double3x3")]
        [JsonDerivedType(typeof(Array_double3x3), "double3x3[]")]
        public partial class Member { }

                    public class Field_Nullable_double3x3 : Field
            {
                [JsonPropertyName("value")]
                public double3x3? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as double3x3?; }

                [JsonIgnore]
                public override Type ValueType => typeof(double3x3?);
            }

            [JsonDerivedType(typeof(Field_Nullable_double3x3), "double3x3?")]
            public partial class Member { }
            
        
        public class Field_float4x4 : Field
        {
            [JsonPropertyName("value")]
            public float4x4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (float4x4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(float4x4);
        }

        public class Array_float4x4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<float4x4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(float4x4);
        }

        [JsonDerivedType(typeof(Field_float4x4), "float4x4")]
        [JsonDerivedType(typeof(Array_float4x4), "float4x4[]")]
        public partial class Member { }

                    public class Field_Nullable_float4x4 : Field
            {
                [JsonPropertyName("value")]
                public float4x4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as float4x4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(float4x4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_float4x4), "float4x4?")]
            public partial class Member { }
            
        
        public class Field_double4x4 : Field
        {
            [JsonPropertyName("value")]
            public double4x4 Value { get; set; }

            [JsonIgnore]
            public override object BoxedValue { get => Value; set => Value = (double4x4)value; }

            [JsonIgnore]
            public override Type ValueType => typeof(double4x4);
        }

        public class Array_double4x4 : SyncArray
        {
            [JsonPropertyName("values")]
            public List<double4x4> Values { get; set; }

            [JsonIgnore]
            public override Type ElementType => typeof(double4x4);
        }

        [JsonDerivedType(typeof(Field_double4x4), "double4x4")]
        [JsonDerivedType(typeof(Array_double4x4), "double4x4[]")]
        public partial class Member { }

                    public class Field_Nullable_double4x4 : Field
            {
                [JsonPropertyName("value")]
                public double4x4? Value { get; set; }

                [JsonIgnore]
                public override object BoxedValue { get => Value; set => Value = value as double4x4?; }

                [JsonIgnore]
                public override Type ValueType => typeof(double4x4?);
            }

            [JsonDerivedType(typeof(Field_Nullable_double4x4), "double4x4?")]
            public partial class Member { }
            
        }
