
// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!


using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;

namespace ResoniteLink
{
    
        public class Field_byte : Field
        {
            [JsonPropertyName("value")]
            public byte Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_byte), "byte")]
        public partial class Member { }

        
        public class Field_ushort : Field
        {
            [JsonPropertyName("value")]
            public ushort Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_ushort), "ushort")]
        public partial class Member { }

        
        public class Field_uint : Field
        {
            [JsonPropertyName("value")]
            public uint Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_uint), "uint")]
        public partial class Member { }

        
        public class Field_ulong : Field
        {
            [JsonPropertyName("value")]
            public ulong Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_ulong), "ulong")]
        public partial class Member { }

        
        public class Field_sbyte : Field
        {
            [JsonPropertyName("value")]
            public sbyte Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_sbyte), "sbyte")]
        public partial class Member { }

        
        public class Field_short : Field
        {
            [JsonPropertyName("value")]
            public short Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_short), "short")]
        public partial class Member { }

        
        public class Field_int : Field
        {
            [JsonPropertyName("value")]
            public int Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_int), "int")]
        public partial class Member { }

        
        public class Field_long : Field
        {
            [JsonPropertyName("value")]
            public long Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_long), "long")]
        public partial class Member { }

        
        public class Field_float : Field
        {
            [JsonPropertyName("value")]
            public float Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_float), "float")]
        public partial class Member { }

        
        public class Field_double : Field
        {
            [JsonPropertyName("value")]
            public double Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_double), "double")]
        public partial class Member { }

        
        public class Field_decimal : Field
        {
            [JsonPropertyName("value")]
            public decimal Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_decimal), "decimal")]
        public partial class Member { }

        
        public class Field_bool : Field
        {
            [JsonPropertyName("value")]
            public bool Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_bool), "bool")]
        public partial class Member { }

        
        public class Field_char : Field
        {
            [JsonPropertyName("value")]
            public char Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_char), "char")]
        public partial class Member { }

        
        public class Field_string : Field
        {
            [JsonPropertyName("value")]
            public string Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_string), "string")]
        public partial class Member { }

        
        public class Field_color : Field
        {
            [JsonPropertyName("value")]
            public color Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_color), "color")]
        public partial class Member { }

        
        public class Field_colorX : Field
        {
            [JsonPropertyName("value")]
            public colorX Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_colorX), "colorX")]
        public partial class Member { }

        
        public class Field_color32 : Field
        {
            [JsonPropertyName("value")]
            public color32 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_color32), "color32")]
        public partial class Member { }

        
        public class Field_float2 : Field
        {
            [JsonPropertyName("value")]
            public float2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_float2), "float2")]
        public partial class Member { }

        
        public class Field_double2 : Field
        {
            [JsonPropertyName("value")]
            public double2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_double2), "double2")]
        public partial class Member { }

        
        public class Field_byte2 : Field
        {
            [JsonPropertyName("value")]
            public byte2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_byte2), "byte2")]
        public partial class Member { }

        
        public class Field_ushort2 : Field
        {
            [JsonPropertyName("value")]
            public ushort2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_ushort2), "ushort2")]
        public partial class Member { }

        
        public class Field_uint2 : Field
        {
            [JsonPropertyName("value")]
            public uint2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_uint2), "uint2")]
        public partial class Member { }

        
        public class Field_ulong2 : Field
        {
            [JsonPropertyName("value")]
            public ulong2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_ulong2), "ulong2")]
        public partial class Member { }

        
        public class Field_sbyte2 : Field
        {
            [JsonPropertyName("value")]
            public sbyte2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_sbyte2), "sbyte2")]
        public partial class Member { }

        
        public class Field_short2 : Field
        {
            [JsonPropertyName("value")]
            public short2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_short2), "short2")]
        public partial class Member { }

        
        public class Field_int2 : Field
        {
            [JsonPropertyName("value")]
            public int2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_int2), "int2")]
        public partial class Member { }

        
        public class Field_long2 : Field
        {
            [JsonPropertyName("value")]
            public long2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_long2), "long2")]
        public partial class Member { }

        
        public class Field_bool2 : Field
        {
            [JsonPropertyName("value")]
            public bool2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_bool2), "bool2")]
        public partial class Member { }

        
        public class Field_float3 : Field
        {
            [JsonPropertyName("value")]
            public float3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_float3), "float3")]
        public partial class Member { }

        
        public class Field_double3 : Field
        {
            [JsonPropertyName("value")]
            public double3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_double3), "double3")]
        public partial class Member { }

        
        public class Field_byte3 : Field
        {
            [JsonPropertyName("value")]
            public byte3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_byte3), "byte3")]
        public partial class Member { }

        
        public class Field_ushort3 : Field
        {
            [JsonPropertyName("value")]
            public ushort3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_ushort3), "ushort3")]
        public partial class Member { }

        
        public class Field_uint3 : Field
        {
            [JsonPropertyName("value")]
            public uint3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_uint3), "uint3")]
        public partial class Member { }

        
        public class Field_ulong3 : Field
        {
            [JsonPropertyName("value")]
            public ulong3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_ulong3), "ulong3")]
        public partial class Member { }

        
        public class Field_sbyte3 : Field
        {
            [JsonPropertyName("value")]
            public sbyte3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_sbyte3), "sbyte3")]
        public partial class Member { }

        
        public class Field_short3 : Field
        {
            [JsonPropertyName("value")]
            public short3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_short3), "short3")]
        public partial class Member { }

        
        public class Field_int3 : Field
        {
            [JsonPropertyName("value")]
            public int3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_int3), "int3")]
        public partial class Member { }

        
        public class Field_long3 : Field
        {
            [JsonPropertyName("value")]
            public long3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_long3), "long3")]
        public partial class Member { }

        
        public class Field_bool3 : Field
        {
            [JsonPropertyName("value")]
            public bool3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_bool3), "bool3")]
        public partial class Member { }

        
        public class Field_float4 : Field
        {
            [JsonPropertyName("value")]
            public float4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_float4), "float4")]
        public partial class Member { }

        
        public class Field_double4 : Field
        {
            [JsonPropertyName("value")]
            public double4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_double4), "double4")]
        public partial class Member { }

        
        public class Field_byte4 : Field
        {
            [JsonPropertyName("value")]
            public byte4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_byte4), "byte4")]
        public partial class Member { }

        
        public class Field_ushort4 : Field
        {
            [JsonPropertyName("value")]
            public ushort4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_ushort4), "ushort4")]
        public partial class Member { }

        
        public class Field_uint4 : Field
        {
            [JsonPropertyName("value")]
            public uint4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_uint4), "uint4")]
        public partial class Member { }

        
        public class Field_ulong4 : Field
        {
            [JsonPropertyName("value")]
            public ulong4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_ulong4), "ulong4")]
        public partial class Member { }

        
        public class Field_sbyte4 : Field
        {
            [JsonPropertyName("value")]
            public sbyte4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_sbyte4), "sbyte4")]
        public partial class Member { }

        
        public class Field_short4 : Field
        {
            [JsonPropertyName("value")]
            public short4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_short4), "short4")]
        public partial class Member { }

        
        public class Field_int4 : Field
        {
            [JsonPropertyName("value")]
            public int4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_int4), "int4")]
        public partial class Member { }

        
        public class Field_long4 : Field
        {
            [JsonPropertyName("value")]
            public long4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_long4), "long4")]
        public partial class Member { }

        
        public class Field_bool4 : Field
        {
            [JsonPropertyName("value")]
            public bool4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_bool4), "bool4")]
        public partial class Member { }

        
        public class Field_floatQ : Field
        {
            [JsonPropertyName("value")]
            public floatQ Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_floatQ), "floatQ")]
        public partial class Member { }

        
        public class Field_doubleQ : Field
        {
            [JsonPropertyName("value")]
            public doubleQ Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_doubleQ), "doubleQ")]
        public partial class Member { }

        
        public class Field_float2x2 : Field
        {
            [JsonPropertyName("value")]
            public float2x2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_float2x2), "float2x2")]
        public partial class Member { }

        
        public class Field_double2x2 : Field
        {
            [JsonPropertyName("value")]
            public double2x2 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_double2x2), "double2x2")]
        public partial class Member { }

        
        public class Field_float3x3 : Field
        {
            [JsonPropertyName("value")]
            public float3x3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_float3x3), "float3x3")]
        public partial class Member { }

        
        public class Field_double3x3 : Field
        {
            [JsonPropertyName("value")]
            public double3x3 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_double3x3), "double3x3")]
        public partial class Member { }

        
        public class Field_float4x4 : Field
        {
            [JsonPropertyName("value")]
            public float4x4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_float4x4), "float4x4")]
        public partial class Member { }

        
        public class Field_double4x4 : Field
        {
            [JsonPropertyName("value")]
            public double4x4 Value { get; set; }

            public override object BoxedValue => Value;
        }

        [JsonDerivedType(typeof(Field_double4x4), "double4x4")]
        public partial class Member { }

        }
